### ISSUE TITLE
[시작화면] 뒤로 가기 버튼 눌러도 나가기 확인 받게 해주세요.

### ISSUE THREAD

**Issue by nepp-plus** [nepp-plus/GuDocIn_Android#31]
다음에 할래요를 누르면 얼럿으로 물어보는것처럼,

뒤로 가기 (백버튼) 눌러도 마찬가지로 얼럿으로 물어봐주세요.

onBackPressed 라는 함수를 이용하시면 됩니다.

**Comment by koolunkle** [comment]
해당 기능 구현 완료하였습니다.
