### ISSUE TITLE
[알림목록화면] 뒤로가기 하면 앱이 아예 종료됩니다.

### ISSUE THREAD

**Issue by nepp-plus** [nepp-plus/GuDocIn_Android#32]
메인화면으로 돌아와야할것 같은데,

그냥 아예 홈화면으로 나가버립니다.

**Comment by koolunkle** [comment]
finish() 코드가 적용되어 있었습니다. 확인 후 해결하였습니다.

**Comment by nepp-plus** [comment]
정상 작동 확인 했습니다. 있다 마스터에 머지 해둘게요~!
