### ISSUE TITLE
[메인화면-홈프래그먼트]   리뷰 목록이 나오게 해주세요.

### ISSUE THREAD

**Issue by nepp-plus** [nepp-plus/GuDocIn_Android#33]
현재는 임시로 상품사진이 나오고 있어, 상품목록처럼 보입니다.

리스트아이템의 모양을 수정해 리뷰 모양으로 보이게 만들어주세요.

상품사진 대신 리뷰에 첨부된 대표이미지를 넣어주세요.

대표 이미지 (썸네일 이미지)가 없는 리뷰는,  기본 이미지를 하나 내려드릴테니

기본 이미지로 쓸만한 사진을 보내주시면 서버에서 반영해드리겠습니다.

**Comment by Ahhyun234** [comment]
수정 완료했습니다

**Comment by Ahhyun234** [comment]
기본 이미지는 아래 URL로 사용 부탁드리겠습니다.
https://drive.google.com/file/d/1PomTQ4emr-XGdKgiK3p17t8dYB3sw8_J/view?usp=sharing

**Comment by nepp-plus** [comment]
수정사항 확인했고, 기본 이미지도 적용해드렸습니다.

이슈 닫겠습니다.
