### ISSUE TITLE
[내 정보 - 작성한 리뷰 목록]  UI를 리뷰 모양이 되도록 개선해주세요.

### ISSUE THREAD

**Issue by nepp-plus** [nepp-plus/GuDocIn_Android#34]
아현님께서 새 UI를 그려주셨을겁니다.

해당 UI로 반영해주시고,

서버에서 내려오는 데이터를 활용해 실 데이터가 그려지게 만들어주세요.

**Comment by ujin-Bang** [comment]
네 개선했습니다.

**Comment by nepp-plus** [comment]
리뷰 목록 확인 했습니다. 이슈 종료 할게요.
